name: Website Production Deployment
on:
  push:
    branches: [master]
    paths:
      - 'porcupine-web/**'
      - '.github/**'

env:
  AZURE_WEBAPP_NAME: lpunionnc-cms                # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'my-app-path'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                          # set this to the node version to use

defaults:
  run:
    working-directory: porcupine-web

jobs:
  build:
    runs-on: ubuntu-20.04    
    steps:
    - uses: actions/checkout@v2
    - name: Install and setup Node version ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3      
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: porcupine-web/package-lock.json
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
        npm run test --if-present
      working-directory: porcupine-web/