name: Strapi Production Deployment
on:
  push:
    branches: [master]
    paths:
      - 'porcupine-cms/**'
      - '.github/**'

env:
  AZURE_WEBAPP_NAME: 'lpunionnc-cms'                # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: 'porcupine-cms/'  # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '16.x'                              # set this to the node version to use

defaults:
  run:
    working-directory: porcupine-cms
jobs:
  build:
    runs-on: ubuntu-20.04    
    steps:
    - uses: actions/checkout@v2
    - name: Install and setup Node version ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3      
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'yarn'
        cache-dependency-path: porcupine-cms/yarn.lock
    #- name: List Directory
    #  run: ls
    - name: install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
        dir: 'porcupine-cms'
    - name: build
      uses: borales/actions-yarn@v4
      with:
        cmd: build # will run `yarn build` command
        dir: 'porcupine-cms'
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_CMS }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        