name: Strapi Production Deployment
on:
  push:
    branches: [master]
    paths:
      - porcupine-cms/**
defaults:
  run:
    working-directory: porcupine-cms
jobs:
  build:
    runs-on: ubuntu-20.04    
    steps:
    - uses: actions/checkout@v2
    - name: Install and setup Node version 14.19.1
      uses: actions/setup-node@v3      
      with:
        node-version: '14.19.1'
        cache: 'yarn'
    - name: install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: build
      uses: borales/actions-yarn@v4
      with:
        cmd: build:prod # will run `yarn install` command